name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: pip install -e '.[all,dev]' pytest
      - run: pytest tests/ -v --tb=short
